### PR TITLE
tang nano20k nes gamepad

### PR DESCRIPTION
**Pull request by fjpolo**
Add NES Gamepad support for NESTang (tang nano 20k)

~~⚠Only gamepad1 was added for now~~

ToDo:
- Update o_button_state to works as a shift register
~~- Add gamepad2~~
- Update verilator tests

### CODE REVIEW

**Comment by fjpolo** [comment]
> Well done! Just curious, have you tested without the level shifter? Sometimes replica controllers work with both voltage levels.

I was going to, would be awesome not needing it, so we can wire it directly, will update the schematic if it works

**Comment by fjpolo** [comment]
Tested directly to LVCMOS3V3 IOs and it's working, at least for [8BitDo N30 2.4g wireless gamepad for original NES
](https://www.8bitdo.com/n30-wireless-for-original-nes/).

- Added joystick#2
- Changed pinout
- Updated wiring
- Updated documentation

**Comment by fjpolo** [comment]
Everything re-tested and working :)

**Comment by nand2mario** [comment]
Great! I'll merge this.

**Comment by nand2mario** [comment]
Just merged #52. Closing this as I believe #52 supercedes this.

**Pull request closed without merging**
