### PR TITLE
Cheats engine

### PR DESCRIPTION
**Pull request by fjpolo**
Cheat module:

- Supports 3 cheats (above 4 it bugs, eneds more work). IN theory it should support more if I fix the bug 🐛
- Barely based in MiSTer's format: [Making your own codes](https://boogermann.github.io/Bible_MiSTer/getting-started/extras/cheat-engine/), I kept the 128bit format, but changed the order, and added cheat Number for the engine
- Added a Wishbone B4 bus, where `iosys.v` acts as the master and `cheat_wizard.v` as a slave. Bus is `128b` wide to send one cheat per Write.
- I added a menu interface in my branch [fjpolo/firmware](https://github.com/fjpolo/nestang/tree/fjpolo/firmware)
- There's also a release for quick testing [[CheatWizard_3cheatSupport_202040604](https://github.com/fjpolo/nestang/releases/tag/v20240604)

I'd appreciate some testing if @nand2mario or @nikitalita have some time :)

I might add some more formal verification tomorrow if I'm felling like it

### CODE REVIEW

**Comment by fjpolo** [comment]
Branch needs to be rebased

**Comment by nand2mario** [comment]
I'll have some time to test it this weekend.

**Comment by fjpolo** [comment]
Rebase done, updated to latest master hash f06aaf8a88489601a51914325cbd8b9c13501797

**Comment by fjpolo** [comment]
So I left the branch at 4 cheats. Again, tested with `Battletoads (USA).nes`

Module toether with its firmware seems scalable enough but I didn't test more than 4 cheats.

I don't know about FV, I'll probably formally verify the wishbone modules, but not for this PR.

**Comment by fjpolo** [comment]
[nestang/fjpolo/firmware](https://github.com/fjpolo/nestang/tree/fjpolo/firmware) updated to match [snestang PR #22 ](https://github.com/nand2mario/snestang/commit/a47afde3ca8bf6a86a1c336df30df31e8681e136)

**Comment by nand2mario** [comment]
This looks good and I'd like to make more changes. So I'm merging this into a new branch.

**Pull request merged**
