### PR TITLE
APU enhancement

### PR DESCRIPTION
**Pull request by fjpolo**
[APU]
- Improved R2A03 APU’s triangle wave and made its mixer linear.
- Improved mapper VRC6’s sawtooth wave. Mixer is already linear.

[VRC6]
- Added mapper. Tested on `Castlevania III (Japan)`. Needs more testing.

[Mapper4/69]
- Disabled APU Enhancement because volume levels saturate

References:
- https://www.youtube.com/watch?v=8RrQrATnXXY&t=500s

### CODE REVIEW

**Comment by fjpolo** [comment]
APU sounds broken in `Little Sisyphus.nes` if Enhancements are disabled

**Comment by nand2mario** [comment]
Can you remove the firmware here and add a separate PR for the firmware in the snestang repo? Let's keep the firmware in a single repo (snestang) for now and make sure the same firmware works for both nestang and snestang. CORE_ID can be used to determine which core is running. In the future we can set up a separate repo for the firmware.

**Comment by fjpolo** [comment]
> Can you remove the firmware here and add a separate PR for the firmware in the snestang repo? Let's keep the firmware in a single repo (snestang) for now and make sure the same firmware works for both nestang and snestang. CORE_ID can be used to determine which core is running. In the future we can set up a separate repo for the firmware.

Will do, this way it will be cleaner. Adding a separate repo has the advantage of adding it as a submodule

**Comment by nikitalita** [comment]
Does this implement the suggestions from this video? https://www.youtube.com/watch?v=8RrQrATnXXY&t=500s

**Comment by fjpolo** [comment]
> Does this implement the suggestions from this video? https://www.youtube.com/watch?v=8RrQrATnXXY&t=500s

Oh yes, that's the idea! I watched that video a long time ago and yesterday came back to my mind.

I'm still on it though. I missunderstood how the module worked so I made some mistakes.

Will changed the draft to a proper PR after fixing, testing, and removing `firmware/` dir to have  aclean PR

**Comment by fjpolo** [comment]
Results are sadly not as good as I'd like :( but at least enabling `APU Enhancements` gives the user a linear mixer, for those who'd prefer it :)

**Comment by fjpolo** [comment]
After shifting Noise Channel output from 6bit to 8bit, it soudns better, at least for me.

**Comment by fjpolo** [comment]
It's finally working as expected. PR contains files from [Cheats PR](https://github.com/nand2mario/nestang/pull/82) because I rebased form there

**Comment by fjpolo** [comment]
Will be added in [#88](https://github.com/nand2mario/nestang/pull/88)

**Pull request closed without merging**
